apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myclusterapp
  name: myclusterapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myclusterapp
  template:
    metadata:
      labels:
        app: myclusterapp
    spec:
      containers:
      - name: myclusterapp
        image: 193500831036.dkr.ecr.us-east-2.amazonaws.com/myownrepo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: myclusterapp
  labels:
    app: myclusterapp
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: myclusterapp
